// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// MessageRoomMember is the golang structure of table message_room_member for DAO operations like Where/Data.
type MessageRoomMember struct {
	g.Meta `orm:"table:message_room_member, do:true"`
	Id     interface{} //
	RoomId interface{} // 房间ID
	UserId interface{} // 成员ID
}
