// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MessageList is the golang structure of table message_list for DAO operations like Where/Data.
type MessageList struct {
	g.Meta           `orm:"table:message_list, do:true"`
	Id               interface{} //
	From             interface{} // 来源
	Mtype            interface{} // 消息类型: 0 用户消息 1 用户进入 2 用户退出 3 错误消息
	Ctype            interface{} // 消息格式: 0 字符串 1 图片
	MsgTime          *gtime.Time // 消息时间
	To               interface{} // 目标用户
	MessageContentId interface{} // 消息ID
	CreatedAt        *gtime.Time //
	UpdatedAt        *gtime.Time //
	DeletedAt        *gtime.Time //
	RoomId           interface{} // 房间号
}
