// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MessageRoom is the golang structure of table message_room for DAO operations like Where/Data.
type MessageRoom struct {
	g.Meta    `orm:"table:message_room, do:true"`
	Id        interface{} //
	Name      interface{} // 房间名称
	Identify  interface{} // 房间唯一标识
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
	DeletedAt *gtime.Time //
}
