// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// MessageContent is the golang structure of table message_content for DAO operations like Where/Data.
type MessageContent struct {
	g.Meta  `orm:"table:message_content, do:true"`
	Id      interface{} //
	Content interface{} //
}
