// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MessageList is the golang structure for table message_list.
type MessageList struct {
	Id               uint64      `json:"id"               ` //
	From             uint64      `json:"from"             ` // 来源
	Mtype            int         `json:"mtype"            ` // 消息类型: 0 用户消息 1 用户进入 2 用户退出 3 错误消息
	Ctype            int         `json:"ctype"            ` // 消息格式: 0 字符串 1 图片
	MsgTime          *gtime.Time `json:"msgTime"          ` // 消息时间
	To               uint64      `json:"to"               ` // 目标用户
	MessageContentId int64       `json:"messageContentId" ` // 消息ID
	CreatedAt        *gtime.Time `json:"createdAt"        ` //
	UpdatedAt        *gtime.Time `json:"updatedAt"        ` //
	DeletedAt        *gtime.Time `json:"deletedAt"        ` //
	RoomId           string      `json:"roomId"           ` // 房间号
}
