// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// MessageContent is the golang structure for table message_content.
type MessageContent struct {
	Id      uint64 `json:"id"      ` //
	Content string `json:"content" ` //
}
