// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MessageRoom is the golang structure for table message_room.
type MessageRoom struct {
	Id        uint64      `json:"id"        ` //
	Name      string      `json:"name"      ` // 房间名称
	Identify  string      `json:"identify"  ` // 房间唯一标识
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
	DeletedAt *gtime.Time `json:"deletedAt" ` //
}
