// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// MessageRoomMember is the golang structure for table message_room_member.
type MessageRoomMember struct {
	Id     uint64 `json:"id"     ` //
	RoomId uint64 `json:"roomId" ` // 房间ID
	UserId uint64 `json:"userId" ` // 成员ID
}
