// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/chat/dao/internal"
)

// internalMessageRoomMemberDao is internal type for wrapping internal DAO implements.
type internalMessageRoomMemberDao = *internal.MessageRoomMemberDao

// messageRoomMemberDao is the data access object for table message_room_member.
// You can define custom methods on it to extend its functionality as you wish.
type messageRoomMemberDao struct {
	internalMessageRoomMemberDao
}

var (
	// MessageRoomMember is globally public accessible object for table message_room_member operations.
	MessageRoomMember = messageRoomMemberDao{
		internal.NewMessageRoomMemberDao(),
	}
)

// Fill with you ideas below.
