// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/chat/dao/internal"
)

// internalMessageRoomDao is internal type for wrapping internal DAO implements.
type internalMessageRoomDao = *internal.MessageRoomDao

// messageRoomDao is the data access object for table message_room.
// You can define custom methods on it to extend its functionality as you wish.
type messageRoomDao struct {
	internalMessageRoomDao
}

var (
	// MessageRoom is globally public accessible object for table message_room operations.
	MessageRoom = messageRoomDao{
		internal.NewMessageRoomDao(),
	}
)

// Fill with you ideas below.
