// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/chat/dao/internal"
)

// internalMessageContentDao is internal type for wrapping internal DAO implements.
type internalMessageContentDao = *internal.MessageContentDao

// messageContentDao is the data access object for table message_content.
// You can define custom methods on it to extend its functionality as you wish.
type messageContentDao struct {
	internalMessageContentDao
}

var (
	// MessageContent is globally public accessible object for table message_content operations.
	MessageContent = messageContentDao{
		internal.NewMessageContentDao(),
	}
)

// Fill with you ideas below.
