// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// MessageContentDao is the data access object for table message_content.
type MessageContentDao struct {
	table   string                // table is the underlying table name of the DAO.
	group   string                // group is the database configuration group name of current DAO.
	columns MessageContentColumns // columns contains all the column names of Table for convenient usage.
}

// MessageContentColumns defines and stores column names for table message_content.
type MessageContentColumns struct {
	Id      string //
	Content string //
}

// messageContentColumns holds the columns for table message_content.
var messageContentColumns = MessageContentColumns{
	Id:      "id",
	Content: "content",
}

// NewMessageContentDao creates and returns a new DAO object for table data access.
func NewMessageContentDao() *MessageContentDao {
	return &MessageContentDao{
		group:   "default",
		table:   "message_content",
		columns: messageContentColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *MessageContentDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *MessageContentDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *MessageContentDao) Columns() MessageContentColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *MessageContentDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *MessageContentDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *MessageContentDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
