// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// MessageListDao is the data access object for table message_list.
type MessageListDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns MessageListColumns // columns contains all the column names of Table for convenient usage.
}

// MessageListColumns defines and stores column names for table message_list.
type MessageListColumns struct {
	Id               string //
	From             string // 来源
	Mtype            string // 消息类型: 0 用户消息 1 用户进入 2 用户退出 3 错误消息
	Ctype            string // 消息格式: 0 字符串 1 图片
	MsgTime          string // 消息时间
	To               string // 目标用户
	MessageContentId string // 消息ID
	CreatedAt        string //
	UpdatedAt        string //
	DeletedAt        string //
	RoomId           string // 房间号
}

// messageListColumns holds the columns for table message_list.
var messageListColumns = MessageListColumns{
	Id:               "id",
	From:             "from",
	Mtype:            "mtype",
	Ctype:            "ctype",
	MsgTime:          "msg_time",
	To:               "to",
	MessageContentId: "message_content_id",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
	DeletedAt:        "deleted_at",
	RoomId:           "room_id",
}

// NewMessageListDao creates and returns a new DAO object for table data access.
func NewMessageListDao() *MessageListDao {
	return &MessageListDao{
		group:   "default",
		table:   "message_list",
		columns: messageListColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *MessageListDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *MessageListDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *MessageListDao) Columns() MessageListColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *MessageListDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *MessageListDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *MessageListDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
