// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// MessageRoomDao is the data access object for table message_room.
type MessageRoomDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns MessageRoomColumns // columns contains all the column names of Table for convenient usage.
}

// MessageRoomColumns defines and stores column names for table message_room.
type MessageRoomColumns struct {
	Id        string //
	Name      string // 房间名称
	Identify  string // 房间唯一标识
	CreatedAt string //
	UpdatedAt string //
	DeletedAt string //
}

// messageRoomColumns holds the columns for table message_room.
var messageRoomColumns = MessageRoomColumns{
	Id:        "id",
	Name:      "name",
	Identify:  "identify",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
}

// NewMessageRoomDao creates and returns a new DAO object for table data access.
func NewMessageRoomDao() *MessageRoomDao {
	return &MessageRoomDao{
		group:   "default",
		table:   "message_room",
		columns: messageRoomColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *MessageRoomDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *MessageRoomDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *MessageRoomDao) Columns() MessageRoomColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *MessageRoomDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *MessageRoomDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *MessageRoomDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
